version: '3.9'

services:
  db:
    image: mysql 
    container_name: wordpress_db
    ports:
       - 3306
    volumes:
        - myvolume:/var/lib/sql
    networks:
        -my network
    environment:
       - MYSQL_ROOT_PASSWORD: Moonlight  
       - MYSQL_DATABASE: wordpress_db 


    
  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - "8080:80"
    networks:
        - mynetwork
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_db  
      WORDPRESS_DB_USER: root  
      WORDPRESS_DB_PASSWORD: Moonlight 
   
networks:
    mynet:
     driver: bridge
volumes:
  myvol:
  
  db_data:  
